# Generated by Django 2.0.2 on 2019-06-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='icone',
            new_name='icon',
        ),
    ]
